build:precise:
  image: node:14

  cache:
    paths:
      - node_modules/

  before_script:
    - apt-get update
    - apt-get install -y -qq python3-dev python3-pip
    - pip3 install --upgrade awscli
    - export PATH=./node_modules/.bin:$PATH
    - cd client && npm install

  deploy_development:
    stage: deploy
    environment:
      name: Development
    only:
      - master 
    script:
      - npm run build
      - aws s3 sync build/ s3://$GIFTI_GLOBAL_BUCKET_NAME --exclude ".DS_Store/*" --cache-control "max-age=120000" --delete
