before_script:
  - apt-get update
  - apt-get install -y -qq python3-dev python3-pip
  - pip3 install --upgrade awscli

cache:
  paths:
    - node_modules/

variables:
  # Use TLS https://docs.gitlab.com/ee/ci/docker/using_docker_build.html#tls-enabled
  DOCKER_HOST: tcp://docker:2376
  DOCKER_TLS_CERTDIR: "/certs"

build:giftiglobal_ui:
  image: node:14
  stage: build
  script:
    - echo $GIFTI_GLOBAL_BUCKET_NAME
    - export PATH=./node_modules/.bin:$PATH
    - cd client && npm install
    - npm run build
  only:
    - merge_requests


build:giftiglobal_server:
  image: docker:19.03.12
  stage: build
  script:
   - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
   - docker info
   - cd server && docker build --cache-from $CI_REGISTRY_IMAGE:latest --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA --tag $CI_REGISTRY_IMAGE:latest .
  only:
   - merge_requests

deploy:giftiglobal_server:
  image: docker:19.03.12
  stage: build
  script:
   - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
   - docker info
   - cd server && docker build --cache-from $CI_REGISTRY_IMAGE:latest --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA --tag $CI_REGISTRY_IMAGE:latest .
   - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
   - docker push $CI_REGISTRY_IMAGE:latest
  only:
   - master

deploy:giftiglobal_ui:
  image: node:14
  stage: deploy
  script: 
    - echo $GIFTI_GLOBAL_BUCKET_NAME
    - export PATH=./node_modules/.bin:$PATH
    - cd client && npm install
    - npm run build
    - aws s3 sync build/ s3://$GIFTI_GLOBAL_BUCKET_NAME --exclude ".DS_Store/*" --cache-control "max-age=120000" --delete
  only:
    - master