<<<<<<< HEAD
#
# @title:  'Gifti Global: CI File'
#
# @author:
# - name: Sai Charan K
#  affiliation: Merit Incentives
#
# @date: 2021-15-04
#
# @tags: [giftiglobal-ui, giftiglobal-server]
#
# @abstract: |
#  There are 2 different stages, (build and deploy) for 2 projects. (React and Python)
#  React project build does an `npm build`. The deploy stage deploys the content of the build folder to S3
#  Python project build does a `docker build`. The deploy stage pushes the image to gitlab container registry.
#
# @version: 1.0
#

build:giftiglobal_ui:
  image: node:14
  stage: build
  before_script:
    - apt-get update
    - apt-get install -y -qq python3-dev python3-pip
    - pip3 install --upgrade awscli
  cache:
    paths:
      - node_modules/
  script:
    - echo $
    - export PATH=./node_modules/.bin:$PATH
    - cd client && npm install
    - npm run build
  only:
    - merge_requests

deploy:giftiglobal_ui:
  image: node:14
  stage: deploy
  before_script:
    - apt-get update
    - apt-get install -y -qq python3-dev python3-pip
    - pip3 install --upgrade awscli
  cache:
    paths:
      - node_modules/
  script: 
    - export PATH=./node_modules/.bin:$PATH
    - cd client && npm install
    - npm run build
    - aws s3 sync build/ s3://$GIFTI_GLOBAL_BUCKET_NAME --exclude ".DS_Store/*" --cache-control "max-age=120000" --delete
  only:
    - master
    - development

build:giftiglobal_server:
  image: docker:19.03.12
  stage: build
  services:
    - docker:19.03.12-dind
  variables:
    DOCKER_HOST: tcp://docker:2376
    DOCKER_TLS_CERTDIR: "/certs"
  script:
   - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
   - cd server && docker build --cache-from $CI_REGISTRY_IMAGE:latest --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA --tag $CI_REGISTRY_IMAGE:latest .
   - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
   - docker push $CI_REGISTRY_IMAGE:latest
  only:
   - merge_requests

deploy:giftiglobal_server:
  stage: deploy
  before_script:
    - apt-get update
    - export IMAGE=$CI_REGISTRY_IMAGE
  script:
    - mkdir -p ~/.ssh
    - echo $CI_REGISTRY_IMAGE
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
    - cat ~/.ssh/id_rsa
    - chmod 700 ~/.ssh/id_rsa
    - eval "$(ssh-agent -s)"
    - ssh-add ~/.ssh/id_rsa
    - ssh-keyscan -H 'gitlab.com' >> ~/.ssh/known_hosts
    - chmod +x ./setup_env.sh
    - chmod +x ./deploy.sh
    - bash ./setup_env.sh
    - scp  -o StrictHostKeyChecking=no -r ./.env ec2-user@$EC2_PUBLIC_IP_ADDRESS:/home/ec2-user/giftiglobal
    - bash ./deploy.sh
  only:
   - master
   - development
=======
>>>>>>> 21975e7177dbd6dd3932c05981d8bcdcd2c91679
