before_script:
  - apt-get update
  - apt-get install -y -qq python3-dev python3-pip
  - pip3 install --upgrade awscli

cache:
  paths:
    - node_modules/

build:giftiglobal_ui:
  image: node:14
  stage: build
  script:
    - export PATH=./node_modules/.bin:$PATH
    - cd client && npm install
    - npm run build

deploy:giftiglobal_ui:
  image: node:14
  stage: deploy
  script: 
    - export PATH=./node_modules/.bin:$PATH
    - cd client && npm install
    - npm run build
    - aws s3 sync build/ s3://$GIFTI_GLOBAL_BUCKET_NAME --exclude ".DS_Store/*" --cache-control "max-age=120000" --delete