version: "3.9"
services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    volumes:
      - ./server:/app/server
    environment:
      PROJECT_NAME: 'User Server'
      WAIT_HOSTS: db:27017
    depends_on:
      - db
  products-server:
    build:
      context: ./products-server
      dockerfile: Dockerfile
    ports:
      - 8001:8001
    volumes:
      - ./products-server:/app/product-server
    environment:
      PROJECT_NAME: 'Products Server'
      WAIT_HOSTS: db:27017
    depends_on:
      - db
  db:
    image: mongo:4.4.4-bionic
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: 'giftiglobal'