version: "3.9"
services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    volumes:
      - ./server:/app/server
    environment:
      PROJECT_NAME: 'GiftiGlobal Server'
      DJANGO_SETTINGS_MODULE: 'GiftiGlobal.settings.development'
      SECRET_KEY: 'abcdefghijklmnopqrstuvwxyz0123456'
      SECRET_ADMIN_URL: 'very_secret_url'
      DB_ENGINE: 'djongo'
      DB_NAME: 'giftiglobal'
      DB_HOST: 'db'
      DB_PORT: '27017'
      DB_USER_NAME: 'root'
      DB_PASS: 'root'
      WAIT_HOSTS: db:27017
    depends_on:
      - db
  db:
    image: mongo:4.4.4-bionic
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: 'giftiglobal'
  mongoexpress:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      MONGO_INITDB_DATABASE: 'giftiglobal'
      ME_CONFIG_MONGODB_ADMINUSERNAME: 'root'
      ME_CONFIG_MONGODB_ADMINPASSWORD: 'root'
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_SERVER: 'db'
      WAIT_HOSTS: db:27017
    depends_on:
      - db