version: "3.9"
services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    volumes:
      - ./server: /app/server
    environment:
      PROJECT_NAME: 'GiftiGlobal Server'
    depends_on:
      - db
  client:
    build:
      context: ./client
    ports:
      - '3000:3000'
    volumes:
      - ./client/src:/app/src
    environment:
      CHOKIDAR_USEPOLLING: 'true'
      REACT_APP_API_URL: 'http://localhost:8080/api'
    stdin_open: true
    depends_on:
      - server
  db:
    image: mongo:4.4.4-bionic
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root

  mongoexpress:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
    