FROM python:3.6.12-alpine3.12
RUN apk update
RUN apk add --no-cache bash
WORKDIR /app
RUN apk add make automake gcc g++ subversion python3-dev
RUN apk add musl-dev libffi-dev openssl-dev
RUN apk add curl dpkg
RUN apk add --no-cache jpeg-dev zlib-dev zlib
RUN apk add --no-cache --virtual .build-deps build-base linux-headers
RUN apk add cairo
RUN apk add cairo-dev pango-dev gdk-pixbuf
RUN apk add openssl-dev rust tcl-dev tiff-dev tk-dev
RUN apk add cargo freetype-dev gdk-pixbuf-dev \
    gettext jpeg-dev lcms2-dev  openjpeg-dev poppler-utils py-cffi
RUN apk update
RUN pip install --upgrade pip
COPY requirements.txt .
RUN pip install -r requirements.txt
COPY . .
EXPOSE 8000
