# Generated by Django 3.0.5 on 2021-04-03 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='accountVerified',
            field=models.BooleanField(default=False),
        ),
    ]
