# Generated by Django 3.0.5 on 2021-04-07 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('giftiglobal', '0002_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
